BEGIN;

ALTER TABLE app.storage_objects
  ADD CONSTRAINT storage_objects_media_type_supported
  CHECK (media_type IN ('application/pdf', 'image/jpeg', 'image/png'));

ALTER TABLE app.document_versions
  DROP CONSTRAINT document_versions_media_type_check,
  ADD CONSTRAINT document_versions_media_type_supported
  CHECK (media_type IN ('application/pdf', 'image/jpeg', 'image/png'));

ALTER TABLE app.document_pages
  DROP CONSTRAINT document_pages_extraction_method_check,
  ADD CONSTRAINT document_pages_extraction_method_supported
  CHECK (extraction_method IN ('pdf_text', 'ocr', 'image_vision'));

ALTER TABLE app.document_pages
  ADD COLUMN visual_description text,
  ADD COLUMN recognized_text text,
  ADD COLUMN analysis_limitations text;

ALTER TABLE app.document_version_states
  DROP CONSTRAINT document_version_states_extraction_method_valid,
  ADD CONSTRAINT document_version_states_extraction_method_valid
  CHECK (extraction_method IS NULL OR extraction_method IN ('pdf_text', 'ocr', 'image_vision'));

COMMENT ON CONSTRAINT document_versions_media_type_supported ON app.document_versions IS
  'Allowlisted PDF and photo formats; upload API validates content signature before persistence.';
COMMENT ON CONSTRAINT document_pages_extraction_method_supported ON app.document_pages IS
  'image_vision denotes model-generated visual description, not a verified literal transcription or professional diagnosis.';
COMMENT ON COLUMN app.document_pages.visual_description IS
  'Visual description generated by AI; distinct from text seen in the image and subject to error.';
COMMENT ON COLUMN app.document_pages.recognized_text IS
  'Text perceived by the vision model; not a guaranteed literal transcription.';
COMMENT ON COLUMN app.document_pages.analysis_limitations IS
  'Uncertainty and limitations returned by image analysis.';

COMMIT;
